### ISSUE TITLE
Error - Attempt to index field 'config'

### ISSUE THREAD

**Issue by skimask9** [aidancz/eolmark.nvim#2] opened 2024-12-06 18:46 UTC
As a result of the update to fix virtual text compatibility
![image](https://github.com/user-attachments/assets/2883f139-854c-4659-ab2e-347ab71f9e18)

**Comment by aidancz** [comment] 2024-12-07 00:47
I tried to reproduce the issue but was unsuccessful.  

Could you please provide the steps to reproduce it? Additionally, could you share your setup?

**Comment by aidancz** [comment] 2024-12-07 14:14
thank you so much for finding this!

after investigation, the issue was caused by mistakenly writing `local M = {}` as `M = {}`.

another plugin made the same mistake, see:

https://github.com/js-everts/cmp-tailwind-colors/issues/5

as a result, the two global M tables conflicted, leading to the bug

this has been fixed in the latest version

**Closed as completed** 2024-12-07 14:13 UTC
